In [1]:
import numpy as np

In [2]:
a = np.random.randn(5)

In [3]:
a

array([ 0.14767922,  0.93538621,  0.60046108, -0.64956536, -0.74210761])

In [4]:
expa = np.exp(a)

In [5]:
expa

array([ 1.159141  ,  2.54819741,  1.82295914,  0.52227273,  0.4761094 ])

In [6]:
answer = expa / expa.sum()

In [7]:
answer

array([ 0.17754601,  0.39030823,  0.27922325,  0.07999668,  0.07292583])

In [8]:
answer.sum()

1.0

In [9]:
A = np.random.randn(100, 5)

In [10]:
A

array([[  3.35164839e-01,   1.63889738e+00,  -5.90552448e-01,
         -2.66876952e+00,   4.33799398e-01],
       [ -6.26477782e-01,  -1.96455252e+00,  -6.76176941e-01,
         -5.12336588e-01,  -4.87051516e-01],
       [  6.63745922e-02,  -1.13091364e+00,  -8.41473668e-01,
         -2.69967375e+00,   9.00723738e-01],
       [  6.34176266e-02,   7.02220424e-01,   9.36724858e-01,
         -6.16021226e-02,   5.40993335e-01],
       [ -1.53801321e+00,  -1.52399861e+00,   3.68465195e-01,
         -1.07631134e-01,  -1.24332204e-01],
       [  1.46333590e+00,  -6.41351521e-01,   1.62690889e+00,
         -1.40587383e+00,  -3.66313109e-01],
       [ -2.46128543e-01,   9.55653779e-01,   2.51086812e-01,
          6.05617275e-01,  -5.58458335e-01],
       [  3.41832102e-01,   9.10015878e-01,   1.08606346e-01,
          1.74126221e-01,   3.50122173e-01],
       [ -2.99916098e-01,   2.18417544e-01,   1.57849539e+00,
          9.93042324e-01,  -1.94162008e-01],
       [  7.87654997e-01,  -8.1613143

In [11]:
expA = np.exp(A)

In [12]:
expA

array([[  1.39817084,   5.14948846,   0.55402113,   0.06933749,
          1.54310929],
       [  0.53447101,   0.14021862,   0.50855753,   0.59909411,
          0.61443538],
       [  1.06862694,   0.32273826,   0.43107479,   0.06722744,
          2.46138386],
       [  1.06547172,   2.01822906,   2.55161083,   0.94025692,
          1.71771228],
       [  0.21480745,   0.21783909,   1.44551433,   0.89795876,
          0.88308643],
       [  4.32034775,   0.52658026,   5.08812244,   0.24515274,
          0.69328569],
       [  0.78182172,   2.6003701 ,   1.28542167,   1.83238294,
          0.57209036],
       [  1.40752396,   2.48436198,   1.11472345,   1.19020579,
          1.41924093],
       [  0.74088038,   1.24410643,   4.84765651,   2.69943455,
          0.82352448],
       [  2.19823551,   0.92162843,   5.69997868,   1.75337859,
          0.48540966],
       [  2.31418003,   1.00733289,   0.41259597,   0.65269373,
          0.16844644],
       [  1.20320659,   0.17101684,  10.035

In [13]:
expA / expA.sum()

array([[  1.85998533e-03,   6.85035956e-03,   7.37013780e-04,
          9.22395985e-05,   2.05279680e-03],
       [  7.11006276e-04,   1.86532692e-04,   6.76533588e-04,
          7.96974315e-04,   8.17382795e-04],
       [  1.42159339e-03,   4.29338393e-04,   5.73458385e-04,
          8.94326016e-05,   3.27437659e-03],
       [  1.41739600e-03,   2.68484818e-03,   3.39440544e-03,
          1.25082288e-03,   2.28507100e-03],
       [  2.85758151e-04,   2.89791131e-04,   1.92296632e-03,
          1.19455368e-03,   1.17476903e-03],
       [  5.74735446e-03,   7.00509213e-04,   6.76872439e-03,
          3.26126457e-04,   9.22277292e-04],
       [  1.04005669e-03,   3.45926984e-03,   1.70999521e-03,
          2.43761727e-03,   7.61051252e-04],
       [  1.87242777e-03,   3.30494436e-03,   1.48291553e-03,
          1.58332961e-03,   1.88801485e-03],
       [  9.85592458e-04,   1.65503359e-03,   6.44883280e-03,
          3.59105519e-03,   1.09553382e-03],
       [  2.92431059e-03,   1.2260414

In [16]:
answer = expA / expA.sum()

In [17]:
answer.sum()

1.0

In [18]:
answer = expA / expA.sum(axis=1)

ValueError: operands could not be broadcast together with shapes (100,5) (100,) 

In [19]:
answer = expA / expA.sum(axis = 1, keepdims = True)

In [20]:
answer

array([[ 0.16044875,  0.59093565,  0.06357735,  0.00795691,  0.17708134],
       [ 0.22299575,  0.058503  ,  0.21218395,  0.24995825,  0.25635905],
       [ 0.24560201,  0.07417478,  0.09907371,  0.01545085,  0.56569865],
       [ 0.12847409,  0.24335714,  0.30767206,  0.11337575,  0.20712096],
       [ 0.0587033 ,  0.05953179,  0.39503496,  0.24539716,  0.2413328 ],
       [ 0.39732857,  0.0484279 ,  0.46793835,  0.02254591,  0.06375927],
       [ 0.11055036,  0.36769488,  0.18175988,  0.25910074,  0.08089414],
       [ 0.18481008,  0.32620059,  0.14636492,  0.15627587,  0.18634854],
       [ 0.07154392,  0.12013849,  0.46811922,  0.26067383,  0.07952454],
       [ 0.19878008,  0.08334019,  0.51543258,  0.15855295,  0.04389419],
       [ 0.50802492,  0.22113673,  0.09057594,  0.14328387,  0.03697854],
       [ 0.08157445,  0.01159452,  0.68036122,  0.05979318,  0.16667663],
       [ 0.05358446,  0.13177202,  0.17306977,  0.06826532,  0.57330842],
       [ 0.07459304,  0.16353489,  0.1

In [21]:
answer.sum(axis = 1)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [22]:
expA.sum(axis=1, keepdims =True)

array([[  8.71412721],
       [  2.39677664],
       [  4.3510513 ],
       [  8.2932808 ],
       [  3.65920606],
       [ 10.87348887],
       [  7.07208679],
       [  7.6160561 ],
       [ 10.35560234],
       [ 11.05863087],
       [  4.55524906],
       [ 14.7497979 ],
       [  5.4386745 ],
       [  3.56025027],
       [  7.13504539],
       [  4.78857359],
       [  9.19003013],
       [  3.65613527],
       [ 12.05056146],
       [  4.22402567],
       [  6.7893535 ],
       [  3.62431519],
       [ 10.80200636],
       [  3.30853455],
       [  6.78730668],
       [  6.68007987],
       [  5.02881276],
       [  5.71623995],
       [  8.96827952],
       [  4.44924832],
       [  6.07087775],
       [  3.51607114],
       [ 17.71728537],
       [  4.45861864],
       [  9.29060531],
       [  5.42561712],
       [  6.54257355],
       [  4.34140728],
       [  3.37893899],
       [  5.89167873],
       [ 10.98811912],
       [ 12.57471663],
       [  9.77990087],
       [  7

In [24]:
expA.sum(axis=1, keepdims =True).shape

(100L, 1L)